# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_auto_20160522_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('libitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libapp.Libitem')),
                ('maker', models.CharField(max_length=100)),
                ('duration', models.IntegerField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, '14A'), (5, 'R'), (6, 'NR')], default=1)),
            ],
            bases=('libapp.libitem',),
        ),
        migrations.AddField(
            model_name='libitem',
            name='num_chkout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libuser',
            name='postalcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fiction'), (2, 'Biography'), (3, 'Self Help'), (4, 'Education'), (5, 'Children'), (6, 'Teen'), (7, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 5, 23)),
        ),
    ]
