# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_auto_20160523_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_Books',
            fields=[
                ('libitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libapp.Libitem')),
                ('b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.Book')),
            ],
            bases=('libapp.libitem',),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pubyr', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Book'), (2, 'DVD'), (3, 'Other')], default=1)),
                ('cost', models.IntegerField()),
                ('num_interested', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 18)),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='itemtype',
            field=models.CharField(choices=[('Book', 'Book'), ('List_of_Books', 'List_of_Books'), ('DVD', 'DVD'), ('Other', 'Other')], default='Book', max_length=6),
        ),
    ]
