# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_auto_20160619_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 25)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
